apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailworker
  namespace: fiaptechchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailworker
  template:
    metadata:
      labels:
        app: emailworker
    spec:
      containers:
        - name: emailworker
          image: fiaphackaton52/emailworker:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
