apiVersion: v1
kind: Service
metadata:
  name: healthscheduling-service
  namespace: fiaptechchallenge
spec:
  selector:
    app: healthscheduling
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081 
  type: NodePort
