apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: fiaptechchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      initContainers:
        - name: wait-for-sqlserver
          image: busybox
          command: [ "sh", "-c", "until nc -z sqlserver-service 1433; do echo 'Aguardando SQL Server...'; sleep 2; done" ]
      
      containers:
        - name: identity
          image: fiaphackaton52/identity:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
