apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: fiaptechchallenge
spec:
  selector:
    app: identity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
