apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  namespace: fiaptechchallenge
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sqlserver"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: fiaptechchallenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
