apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: fiaptechchallenge
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
